network:
  version: 2
  renderer: networkd
  ethernets:
    enX0:
      addresses:
        - xxx.xxx.xxx.xxx/24
      nameservers:
        addresses: [xxx.xxx.xxx.1]
      routes:
        - to: default
          via: xxx.xxx.xxx.1
